# Generated by Django 6.1.1 on 2026-09-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address_line1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('MA', 'Massachusetts'), ('RI', 'Rhode Island'), ('NH', 'New Hampshire'), ('CT', 'Connecticut'), ('ME', 'Maine'), ('VT', 'Vermont'), ('NY', 'New York'), ('OTHER', 'Other')], default='MA', max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('reason', models.CharField(choices=[('water_leak', 'Water Leak (Outside Home)'), ('sewer_drain', 'Sewer/Drain Break or Back Up'), ('drainage', 'Drainage Issues'), ('excavation_quote', 'Excavation Quote'), ('other', 'Other')], max_length=30)),
                ('property_type', models.CharField(choices=[('private', 'Private Property'), ('commercial', 'Commercial Property'), ('municipal', 'Municipal / Government')], default='private', max_length=30)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='enquiries/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
