# Generated by Django 6.1.1 on 2026-09-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrf', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
