# Generated by Django 6.1.1 on 2026-09-04 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrf', '0003_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(blank=True, help_text='Staff name to show as the author', max_length=100)),
                ('excerpt', models.CharField(help_text='Short summary shown on the blog list page', max_length=250)),
                ('content', models.TextField(help_text='Main body of the post. Line breaks are preserved.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
