# Generated by Django 6.1.1 on 2026-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrf', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, help_text='Optional, shown under the photo', max_length=200)),
                ('category', models.CharField(choices=[('storm-drainage', 'Storm Drainage'), ('helical-pile-installation', 'Helical Pile Installation'), ('demolition', 'Demolition'), ('site-development', 'Site Development'), ('retaining-walls', 'Retaining Walls'), ('emergency-utility-repair', 'Emergency Utility Repair'), ('foundations', 'Foundations'), ('water-sewer-installations', 'Water & Sewer Installations'), ('ledge-breaking', 'Ledge Breaking'), ('general', 'General / Other')], default='general', max_length=40)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
