# Generated by Django 6.1.1 on 2026-09-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrf', '0005_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(help_text='Short summary shown on the blog list page, works as meta description for Search Engine Optimisation. Make it a proper sentence but try to catch as many keywords as possible', max_length=250),
        ),
    ]
