# Generated by Django 6.1.1 on 2026-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrf', '0006_remove_galleryimage_category_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_historical',
            field=models.BooleanField(default=False, help_text='Check for old/archival company photos, shown on the About page'),
        ),
    ]
